
name: Release

env:
  TZ: Asia/Shanghai

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set the environment variable
        shell: pwsh
        run: |
          $commitId = $env:GITHUB_SHA
          $shortCommitId = $commitId.Substring(0, 7)
          echo "Setting COMMIT_ID=$shortCommitId"
          echo "COMMIT_ID=$shortCommitId" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Export Modpack File
        shell: cmd
        run: |
          call ./main.bat

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: Modpack-Artifact # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ./*.mrpack
          # The desired behavior if no files are found using the provided path.

  nightly-release:
    permissions: write-all
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/') != true
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: Modpack-Artifact

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly-release"
          prerelease: true
          title: "nightly-release"
          files: |
            *.mrpack

  release:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v5
        with:
          name: Modpack-Artifact

      - name: Release Action
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.mrpack
          body_path: CHANGELOG.md
